services:
    - docker

before_install:
    - docker --version

script:
    - docker build -t polinux/haproxy-sa .

    - docker run -d --name hpsa -p 80:80 polinux/haproxy-sa
    # TEST
    - while true; do if docker logs hpsa | grep "HAProxy started with"; then break; else sleep 1; fi done
    - curl -sSLi http://localhost:80 | grep '200 OK' 